"""empty message

Revision ID: 66fe59e81a36
Revises: e95aa893e969
Create Date: 2021-07-08 15:41:15.782282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66fe59e81a36'
down_revision = 'e95aa893e969'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('car', sa.Column('name', sa.String(length=150), nullable=True))
    op.alter_column('instrument', 'instrumentid',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.alter_column('instrument', 'user_token',
               existing_type=sa.VARCHAR(length=150),
               nullable=False)
    op.create_foreign_key(None, 'instrument', 'user', ['user_token'], ['token'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'instrument', type_='foreignkey')
    op.alter_column('instrument', 'user_token',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.alter_column('instrument', 'instrumentid',
               existing_type=sa.VARCHAR(length=150),
               nullable=True)
    op.drop_column('car', 'name')
    # ### end Alembic commands ###
